defaults:
  - override job_logging: rich_logging

run:
  dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
sweep:
  dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  subdir: ${hydra.job.num}
