defaults:
  - hf_lm
  - _self_

# https://huggingface.co/google/flan-t5-large
model_name_or_path: google/flan-t5-large
name: flan-t5-large

# tokenizer_kwargs:
#   padding: max_length
#   truncation: true
#   return_tensors: pt

linearize: true
