model:
  _target_: transformers.RobertaModel.from_pretrained
  pretrained_model_name_or_path: ${..model_name_or_path}

tokenizer:
  _target_: transformers.RobertaTokenizer.from_pretrained
  pretrained_model_name_or_path: ${..model_name_or_path}

# https://huggingface.co/roberta-base
model_name_or_path: roberta-base
name: ${.model_name_or_path}

tokenizer_kwargs:
  padding: max_length
  truncation: true
  return_tensors: pt

linearize: false
