name: glue-cola

datasets:
  _target_: datasets.load_dataset
  path: glue
  name: cola

preprocessor:
  _target_: src.tasks.CoLA_Preprocessor
  template_file: glue_v1/cola.json

map_kwargs:
  remove_columns: ["sentence", "label", "idx"]
  batched: true
  num_proc: 1
  desc: Running tokenizer on dataset
