name: glue-rte

datasets:
  _target_: datasets.load_dataset
  path: glue
  name: rte

preprocessor:
  _target_: src.tasks.RTE_Preprocessor
  template_file: glue_v1/rte.json

map_kwargs:
  remove_columns: ["sentence1", "sentence2", "label", "idx"]
  batched: true
  num_proc: 1
  desc: Running tokenizer on dataset
