defaults:
  - hydra: default
  - _self_

fast_dev_run: false

exp_name: null
version: null

model: "ViT-B-32"
device: cuda
data_location: ???
eval_datasets: null
train_dataset: null
test_datasets:
  - SUN397
  - Cars
  - RESISC45
  - EuroSAT
  - SVHN
  - GTSRB
  - MNIST
  - DTD
datasets: ${test_datasets}

ls: 0.0
warmup_length: 500
epochs: 10
load: null
save: ???

# optimizer
lr: 0.001 # learning rate
wd: 0  # weight decay

# dataloader
batch_size: 16
num_workers: 4

sam_retraining: false

# corruption type on dataset (string)
corruption: null
